[internal] Update GitHub Actions workflow files

diff --git a/.github/workflows/nightly-sdk-generation.yml b/.github/workflows/nightly-sdk-generation.yml
--- a/.github/workflows/nightly-sdk-generation.yml
+++ b/.github/workflows/nightly-sdk-generation.yml
@@ -1,86 +1,96 @@
 name: nightly-sdk-generation
-"on":
+on:
   schedule:
-    - cron: 35 4 * * *
+  - cron: 35 4 * * 1-5
   workflow_dispatch: {}
-
 env:
   GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
   PROVIDER: aws-native
-
+  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
+  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
+  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
+  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
+  TRAVIS_OS_NAME: linux
+  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
+  AWS_REGION: us-west-2
+  PULUMI_API: https://api.pulumi-staging.io
 jobs:
   generate-sdk:
-    name: prerequisites
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        goversion: [1.17.x]
+    name: generate-sdk
     steps:
-      - name: Checkout Repo
-        uses: actions/checkout@v2
-        with:
-          lfs: true
-      - name: Unshallow clone for tags
-        run: git fetch --prune --unshallow --tags
-      - name: Install Go
-        uses: actions/setup-go@v2
-        with:
-          go-version: ${{ matrix.goversion }}
-      - name: Install pulumictl
-        uses: jaxxstorm/action-install-gh-release@v1.1.0
-        with:
-          repo: pulumi/pulumictl
-      - name: Install Pulumi CLI
-        uses: pulumi/setup-pulumi@v2
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-region: us-west-2
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          role-duration-seconds: 3600
-          role-session-name: ${{ env.PROVIDER }}@githubActions
-          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
-      - name: Cleanup SDK folder
-        run: make clean
-      - name: Preparing Git Branch
-        run: |
-          git config --local user.email "bot@pulumi.com"
-          git config --local user.name "pulumi-bot"
-          git checkout -b generate-sdk/${{ github.run_id }}-${{ github.run_number }}
-      - name: commit changes
-        run: |
-          git add .
-          git commit -m "Preparing the SDK folder for regeneration"
-          git push origin generate-sdk/${{ github.run_id }}-${{ github.run_number }}
-      - name: Discovery
-        run: make discovery
-      - name: Build codegen binaries
-        run: make codegen
-      - name: Build Schema + SDKs
-        run: make local_generate
-      - name: Git submodule commit hash
-        id: vars
-        run: echo ::set-output name=commit-hash::$(git rev-parse HEAD)
-        working-directory: aws-cloudformation-user-guide
-      - name: commit changes
-        run: |
-          git add .
-          git commit -m "Regenerating SDK based on aws-cloudformation-user-guide @ ${{ steps.vars.outputs.commit-hash }}"
-          git push origin generate-sdk/${{ github.run_id }}-${{ github.run_number }}
-      - name: Create PR
-        id: create-pr
-        uses: repo-sync/pull-request@v2.6.2
-        with:
-          source_branch: "generate-sdk/${{ github.run_id }}-${{ github.run_number }}"
-          destination_branch: "master"
-          pr_title: "Automated SDK generation @ aws-cloudformation-user-guide ${{ steps.vars.outputs.commit-hash }}"
-          github_token: ${{ secrets.PULUMI_BOT_TOKEN }}
-      - name: Set Automerge
-        if: steps.create-pr.outputs.has_changed_files
-        uses: peter-evans/enable-pull-request-automerge@v1
-        with:
-          token: ${{ secrets.PULUMI_BOT_TOKEN }}
-          pull-request-number: ${{ steps.create-pr.outputs.pr_number }}
-          repository: ${{ github.repository }}
-          merge-method: squash
+    - name: Checkout Repo
+      uses: actions/checkout@v2
+      with:
+        lfs: true
+    - name: Install Go
+      uses: actions/setup-go@v2
+      with:
+        go-version: 1.19.x
+    - name: Install pulumictl
+      uses: jaxxstorm/action-install-gh-release@v1.5.0
+      with:
+        repo: pulumi/pulumictl
+    - name: Install Pulumi CLI
+      uses: pulumi/action-install-pulumi-cli@v2
+    - name: Cleanup SDK Folder
+      run: make clean
+    - name: Preparing Git Branch and initial commit
+      run: >-
+        git config --local user.email "bot@pulumi.com"
+
+        git config --local user.name "pulumi-bot"
+
+        git checkout -b generate-sdk/${{ github.run_id }}-${{ github.run_number }}
+
+        git add . && git commit -m "Preparing the SDK folder for regeneration"
+    - name: Discovery
+      run: make discovery
+    - name: Build codegen binaries
+      run: make codegen
+    - name: Build Schema + SDKs
+      run: make local_generate
+    - name: Git submodule commit hash
+      id: vars
+      run: echo ::set-output name=commit-hash::$(git rev-parse HEAD)
+      working-directory: aws-cloudformation-user-guide
+    - name: Commit changes
+      run: >-
+        git add sdk
+
+        git commit -m "Regenerating SDKs based on aws-cloudformation-user-guide @ ${{ steps.vars.outputs.commit-hash }}" || echo "ignore commit failure, may be empty"
+
+        git add .
+
+        git commit -m "Regenerating based on aws-cloudformation-user-guide @ ${{ steps.vars.outputs.commit-hash }}"
+
+        git push origin generate-sdk/${{ github.run_id }}-${{ github.run_number }}
+    - name: Create PR
+      id: create-pr
+      uses: repo-sync/pull-request@v2.6.2
+      with:
+        destination_branch: master
+        github_token: ${{ secrets.PULUMI_BOT_TOKEN }}
+        pr_body: "*Automated PR*"
+        pr_title: Automated SDK generation @ aws-cloudformation-user-guide ${{
+          steps.vars.outputs.commit-hash }}
+        author_name: pulumi-bot
+        source_branch: generate-sdk/${{ github.run_id }}-${{ github.run_number }}
+    - name: Set AutoMerge
+      if: steps.create-pr.outputs.has_changed_files
+      uses: peter-evans/enable-pull-request-automerge@v1
+      with:
+        token: ${{ secrets.PULUMI_BOT_TOKEN }}
+        pull-request-number: ${{ steps.create-pr.outputs.pr_number }}
+        repository: ${{ github.repository }}
+        merge-method: squash
+    - if: failure() && github.event_name == 'push'
+      name: Notify Slack
+      uses: 8398a7/action-slack@v3
+      with:
+        author_name: Failure during automated SDK generation
+        fields: repo,commit,author,action
+        status: ${{ job.status }}
